import PDFDocument from 'pdfkit'
import { Readable } from 'stream'
import { prisma } from '@/lib/db'
import { getStorageAdapter } from '@/lib/storage'

export interface PacketOptions {
  packetId: string
  userId: string
  includeTimeline?: boolean
  includeExhibits?: boolean
}

export interface PacketMetadata {
  title: string
  description: string
  category: 'LEGAL' | 'MEDICAL' | 'FINANCIAL' | 'PERSONAL' | 'OTHER'
  createdAt: Date
  documentCount: number
  eventCount: number
}

export class PacketGenerator {
  /**
   * Generate a PDF packet from a saved packet record
   */
  async generatePacket(options: PacketOptions): Promise<Buffer> {
    const { packetId, userId, includeTimeline = true, includeExhibits = true } = options

    // Get packet data
    const packet = await prisma.packet.findUnique({
      where: { id: packetId, userId },
      include: {
        documents: {
          include: {
            events: {
              orderBy: { eventDate: 'asc' },
            },
          },
        },
      },
    })

    if (!packet) {
      throw new Error('Packet not found')
    }

    // Create PDF document
    const doc = new PDFDocument({
      size: 'LETTER',
      margins: {
        top: 72,
        bottom: 72,
        left: 72,
        right: 72,
      },
      info: {
        Title: packet.title,
        Author: 'Life-Doc-Vault',
        Subject: packet.description || 'Document Packet',
        CreationDate: new Date(),
      },
    })

    // Collect PDF chunks
    const chunks: Buffer[] = []
    doc.on('data', (chunk) => chunks.push(chunk))

    // Generate cover page
    this.generateCoverPage(doc, {
      title: packet.title,
      description: packet.description || '',
      category: packet.category || 'OTHER',
      createdAt: packet.createdAt,
      documentCount: packet.documents.length,
      eventCount: packet.documents.reduce((sum, doc) => sum + doc.events.length, 0),
    })

    // Generate table of contents
    doc.addPage()
    this.generateTableOfContents(doc, packet)

    // Generate timeline if requested
    if (includeTimeline && packet.documents.some((doc) => doc.events.length > 0)) {
      doc.addPage()
      this.generateTimeline(doc, packet)
    }

    // Generate document summaries
    doc.addPage()
    this.generateDocumentSummaries(doc, packet)

    // Add exhibits (document content) if requested
    if (includeExhibits) {
      // Note: Adding full document PDFs would require pdf-lib for merging
      // For now, we'll add a placeholder page for each document
      for (let i = 0; i < packet.documents.length; i++) {
        const document = packet.documents[i]
        doc.addPage()
        this.generateExhibitPage(doc, document, i + 1)
      }
    }

    // Finalize PDF
    doc.end()

    // Wait for PDF generation to complete
    return new Promise((resolve, reject) => {
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(chunks)
        resolve(pdfBuffer)
      })
      doc.on('error', reject)
    })
  }

  /**
   * Generate cover page
   */
  private generateCoverPage(doc: PDFKit.PDFDocument, metadata: PacketMetadata) {
    // Title
    doc
      .fontSize(28)
      .font('Helvetica-Bold')
      .text(metadata.title, { align: 'center' })
      .moveDown(2)

    // Category badge
    doc
      .fontSize(12)
      .font('Helvetica')
      .text(`Category: ${metadata.category}`, { align: 'center' })
      .moveDown(1)

    // Description
    if (metadata.description) {
      doc
        .fontSize(14)
        .font('Helvetica')
        .text(metadata.description, {
          align: 'center',
          width: 400,
        })
        .moveDown(2)
    }

    // Stats box
    const statsY = doc.y + 50
    doc
      .fontSize(12)
      .font('Helvetica-Bold')
      .text('Packet Summary', 72, statsY)
      .moveDown(0.5)

    doc.font('Helvetica').fontSize(11)
    doc.text(`Documents Included: ${metadata.documentCount}`)
    doc.text(`Events Tracked: ${metadata.eventCount}`)
    doc.text(`Generated: ${metadata.createdAt.toLocaleDateString()}`)

    // Footer
    doc
      .fontSize(10)
      .font('Helvetica')
      .text('Generated by Life-Doc-Vault', 72, doc.page.height - 100, {
        align: 'center',
      })
      .text('Secure Personal Document Management', {
        align: 'center',
      })
  }

  /**
   * Generate table of contents
   */
  private generateTableOfContents(doc: PDFKit.PDFDocument, packet: any) {
    doc.fontSize(20).font('Helvetica-Bold').text('Table of Contents').moveDown(1)

    let pageNum = 3 // Start after cover and ToC

    // Timeline section
    if (packet.documents.some((doc: any) => doc.events.length > 0)) {
      doc
        .fontSize(12)
        .font('Helvetica')
        .text(`Timeline of Events`, 72, doc.y, { continued: true })
        .text(`${pageNum}`, 500, doc.y, { align: 'right' })
        .moveDown(0.5)
      pageNum++
    }

    // Document summaries
    doc
      .fontSize(12)
      .font('Helvetica')
      .text(`Document Summaries`, 72, doc.y, { continued: true })
      .text(`${pageNum}`, 500, doc.y, { align: 'right' })
      .moveDown(0.5)
    pageNum++

    // Exhibits
    doc.moveDown(0.5)
    doc.fontSize(14).font('Helvetica-Bold').text('Exhibits').moveDown(0.5)

    packet.documents.forEach((document: any, index: number) => {
      doc
        .fontSize(11)
        .font('Helvetica')
        .text(`Exhibit ${index + 1}: ${document.originalName}`, 72, doc.y, {
          continued: true,
        })
        .text(`${pageNum}`, 500, doc.y, { align: 'right' })
        .moveDown(0.3)
      pageNum++
    })
  }

  /**
   * Generate timeline section
   */
  private generateTimeline(doc: PDFKit.PDFDocument, packet: any) {
    doc.fontSize(20).font('Helvetica-Bold').text('Timeline of Events').moveDown(1)

    // Collect all events from all documents
    const allEvents: any[] = []
    packet.documents.forEach((document: any) => {
      document.events.forEach((event: any) => {
        allEvents.push({
          ...event,
          documentName: document.originalName,
        })
      })
    })

    // Sort by date
    allEvents.sort((a, b) => new Date(a.eventDate).getTime() - new Date(b.eventDate).getTime())

    // Render events
    allEvents.forEach((event) => {
      const eventDate = new Date(event.eventDate)
      const dateStr = eventDate.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      })

      doc
        .fontSize(11)
        .font('Helvetica-Bold')
        .text(dateStr)
        .font('Helvetica')
        .fontSize(10)

      if (event.eventTime) {
        doc.text(`Time: ${event.eventTime}`)
      }

      doc.text(`Description: ${event.description}`)

      if (event.entities && event.entities.length > 0) {
        doc.text(`Involved: ${event.entities.join(', ')}`)
      }

      doc.text(`Source: ${event.documentName}`)
      doc.text(`Confidence: ${Math.round(event.confidence * 100)}%`)
      doc.moveDown(0.8)

      // Add page break if needed
      if (doc.y > doc.page.height - 100) {
        doc.addPage()
      }
    })
  }

  /**
   * Generate document summaries section
   */
  private generateDocumentSummaries(doc: PDFKit.PDFDocument, packet: any) {
    doc.fontSize(20).font('Helvetica-Bold').text('Document Summaries').moveDown(1)

    packet.documents.forEach((document: any, index: number) => {
      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .text(`${index + 1}. ${document.originalName}`)
        .moveDown(0.5)

      doc.fontSize(10).font('Helvetica')

      // Document metadata
      doc.text(`File Type: ${document.mimeType}`)
      doc.text(`Size: ${this.formatFileSize(Number(document.fileSize))}`)
      doc.text(`Uploaded: ${new Date(document.uploadedAt).toLocaleDateString()}`)

      if (document.category) {
        doc.text(`Category: ${document.category}`)
      }

      // AI analysis summary
      if (document.extractedData && document.extractedData.summary) {
        doc.moveDown(0.5)
        doc.fontSize(11).font('Helvetica-Bold').text('Summary:')
        doc.fontSize(10).font('Helvetica').text(document.extractedData.summary)
      }

      // Events
      if (document.events.length > 0) {
        doc.moveDown(0.5)
        doc
          .fontSize(11)
          .font('Helvetica-Bold')
          .text(`Events Extracted: ${document.events.length}`)
      }

      doc.moveDown(1)

      // Page break if needed
      if (doc.y > doc.page.height - 150) {
        doc.addPage()
      }
    })
  }

  /**
   * Generate exhibit page (placeholder for actual document)
   */
  private generateExhibitPage(doc: PDFKit.PDFDocument, document: any, exhibitNumber: number) {
    doc
      .fontSize(20)
      .font('Helvetica-Bold')
      .text(`Exhibit ${exhibitNumber}`, { align: 'center' })
      .moveDown(1)

    doc
      .fontSize(14)
      .font('Helvetica')
      .text(document.originalName, { align: 'center' })
      .moveDown(2)

    doc.fontSize(11).font('Helvetica')
    doc.text(`File: ${document.filename}`)
    doc.text(`Type: ${document.mimeType}`)
    doc.text(`Size: ${this.formatFileSize(Number(document.fileSize))}`)
    doc.text(`Uploaded: ${new Date(document.uploadedAt).toLocaleDateString()}`)
    doc.text(`Hash: ${document.fileHash.substring(0, 16)}...`)

    doc.moveDown(2)

    // OCR text preview if available
    if (document.ocrText) {
      doc.fontSize(11).font('Helvetica-Bold').text('Extracted Text Preview:')
      doc.moveDown(0.5)
      doc
        .fontSize(9)
        .font('Helvetica')
        .text(document.ocrText.substring(0, 1000) + (document.ocrText.length > 1000 ? '...' : ''))
    } else {
      doc
        .fontSize(11)
        .font('Helvetica-Oblique')
        .text('[Original document would be embedded here]', {
          align: 'center',
        })
    }
  }

  /**
   * Format file size for display
   */
  private formatFileSize(bytes: number): string {
    if (bytes === 0) return '0 Bytes'

    const k = 1024
    const sizes = ['Bytes', 'KB', 'MB', 'GB']
    const i = Math.floor(Math.log(bytes) / Math.log(k))

    return Math.round((bytes / Math.pow(k, i)) * 100) / 100 + ' ' + sizes[i]
  }
}

export const packetGenerator = new PacketGenerator()
